#!/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

nitrogen --restore &
compton &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Thunar desktop='^3' state=floating follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a mplayer2 state=floating follow=on
bspc rule -a mpv state=floating follow=on
