#!/bin/sh

$HOME/.config/polybar/launch.sh

# autostart
sxhkd &
xsetroot -cursor_name left_ptr 
nitrogen --restore &
compton -f &
guake &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         3
bspc config window_gap           16
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Xfce4-terminal desktop='^1' follow=on
bspc rule -a Guake desktop='^1' follow=on
bspc rule -a mpv desktop='^4' state=floating follow=on
bspc rule -a Org.gnome.Nautilus desktop='^3' state=floating follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a ffplay desktop='^4' follow=off
bspc rule -a mplayer desktop='^4' state=floating follow=on
bspc rule -a Evince desktop='^7' state=floating follow=on
bspc rule -a Nitrogen state=floating desktop='^5' follow=on
bspc rule -a Pavucontrol desktop='^5' state=floating follow=on

# border colors 
bspc config normal_border_color "#44475a"
bspc config focused_border_color "#005577"

