#!/bin/sh

$HOME/.config/polybar/launch.sh

sxhkd &
setxkbmap -option caps:escape &
setxkbmap gb &
nitrogen --restore &
compton &

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pcmanfm desktop='^3' state=floating follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a mplayer2 state=floating follow=on
bspc rule -a Evince state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a Nitrogen state=floating desktop='^5' follow=on

# set theme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#005577"
bspc config presel_feedback_color "#6272a4"

#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd"
#setting theme done

